#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

pdflatex monitorizacion-jce.tex && pdflatex monitorizacion-jce.tex &&  pdflatex monitorizacion-jce.tex && bibtex monitorizacion-jce && pdflatex monitorizacion-jce.tex && pdflatex monitorizacion-jce.tex && pdflatex monitorizacion-jce.tex && echo "-----------------------------" 
