#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex monitorizacion-jce.tex && latex monitorizacion-jce.tex &&  latex monitorizacion-jce.tex && bibtex monitorizacion-jce && latex monitorizacion-jce.tex && latex monitorizacion-jce.tex && latex monitorizacion-jce.tex && echo "-----------------------------" && dvips monitorizacion-jce.dvi -o && ps2pdf monitorizacion-jce.ps && echo " "
